[tasks.start-servers]
command = "docker-compose"
args = ["-f", "tests/docker/docker-compose.yaml", "up", "-d"]

[tasks.stop-servers]
command = "docker-compose"
args = ["-f", "tests/docker/docker-compose.yaml", "down"]

[tasks.sleep]
command = "sleep"
args = ["5"]
dependencies = ["start-servers"]

[tasks.test-int]
command = "cargo"
args = ["test", "--tests"]
dependencies = ["sleep"]

[tasks.tests]
description = "Run integration tests with docker-compose"
run_task = { name = ["test-int"], fork = true, cleanup_task = "stop-servers" }

[tasks.setup-local-kind]
command = "kind"
args = ["create", "cluster", "--name", "kind", "--config", "operations/kubernetes/local/kind-config.yaml"]

[tasks.setup-local-kind-ingress]
command = "kubectl"
args = ["apply", "-f", "https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml"]

[tasks.setup-local-kind-namespace]
command = "kubectl"
args = ["create", "namespace", "dev"]

[tasks.setup-local-kind-api-key]
command = "kubectl"
args = ["create", "secret", "-n", "dev", "generic", "api-key-server-secret", "--from-literal", "api-key=1234"]

[tasks.edit-kustomize-local]
cwd = "operations/kubernetes/overlays/local"
command = "kustomize"
args = ["edit", "set", "image", "secret-shared-server=ghcr.io/jproyo/secret-shared-server:latest"]

[tasks.build-kustomize-local]
command = "kustomize"
args = ["build", "operations/kubernetes/overlays/local", "-o", "test.yaml"]



