name: Docker Build and Push

on:
  workflow_call:
    inputs:
      module-path:
        required: false
        type: string
        default: ''
      build-args:
        required: false
        type: string
        default: ''
      docker-file-path:
        required: false
        type: string
        default: 'operations/docker/Dockerfile'
      docker-image-name:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT_ID }}
      - run: |-
          gcloud --quiet auth configure-docker europe-west4-docker.pkg.dev/${{ secrets.GKE_PROJECT_ID}}/default
      - name: Current branch sha
        if: github.event_name != 'release'
        run: |
          echo "DOCKER_TAG_IMAGE=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: Current Tag
        if: github.event_name == 'release'
        run: |
          echo "DOCKER_TAG_IMAGE=${{  github.ref_name }}" >> $GITHUB_ENV
      - name: Docker Build and Push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ inputs.module-path }}"
          build-args: ${{ inputs.build-args }}
          file: ${{ inputs.docker-file-path }}
          push: true
          tags: europe-west4-docker.pkg.dev/${{ secrets.GKE_PROJECT_ID}}/default/${{inputs.docker-image-name}}:${{env.DOCKER_TAG_IMAGE}}


