name: BUILD - Shared Secret

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-rust:
    uses: ./.github/workflows/build-rust.yml
    secrets: inherit
  build-docker:
    needs: build-rust
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
    with:
      docker-image-name: secret-shared-server
      docker-file-path: server/operations/docker/Dockerfile
    permissions:
      contents: 'read'
      id-token: 'write'
  deploy:
    needs:
      - build-docker
    uses: ./.github/workflows/build-k8s-deploy.yml
    secrets: inherit
    with:
      docker-image-names: "secret-shared-server"
      overlays-folder: 'server/operations/kubernetes/overlays'
      manifest-file: deployment.yaml
      manifest-folder: server



